print("Traceback (most recent call last):")
print(" File './models-buggy/object_detection/models/faster_rcnn_resnet_v1_feature_extractor_test.py', line 82, in test_extract_proposal_features_stride_eight")
print("  preprocessed_inputs, scope='TestScope')")
print(" File '/home/metadata/TensorFlow-Program-Bugs/Github/APIM-1/models-buggy/object_detection/meta_architectures/faster_rcnn_meta_arch.py', line 131, in extract_proposal_features")
print("  return self._extract_proposal_features(preprocessed_inputs, scope)")
print(" File '/home/metadata/TensorFlow-Program-Bugs/Github/APIM-1/models-buggy/object_detection/models/faster_rcnn_resnet_v1_feature_extractor.py', line 125, in _extract_proposal_features")
print("  scope=var_scope)")
print(" File '/home/metadata/TensorFlow-Program-Bugs/Github/APIM-1/models-buggy/slim/nets/resnet_v1.py', line 280, in resnet_v1_101")
print("  reuse=reuse, scope=scope)")
print(" File '/home/metadata/TensorFlow-Program-Bugs/Github/APIM-1/models-buggy/slim/nets/resnet_v1.py', line 204, in resnet_v1")
print("  logits = tf.squeeze(net, [1, 2], name='SpatialSqueeze')")
print("ValueError: Can not squeeze dim[1], expected a dimension of 1, got 28 for 'TestScope/resnet_v1_101/resnet_v1_101/SpatialSqueeze' (op: 'Squeeze') with input shapes: [4,28,28,2048].")
